CREATE DATABASE tiozeiros;

CREATE TABLE usuarios(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	login VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	CONSTRAINT USUARIOS_ID_PK PRIMARY KEY(id)
);

CREATE TABLE jogadores(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	finalização VARCHAR(11) NOT NULL,
	velocidade MONEY NOT NULL,
	passe MONEY NOT NULL,
	marcação MONEY NOT NULL,
	CONSTRAINT JOGADORES_ID_PK PRIMARY KEY(id)
);