CREATE DATABASE usuario;

CREATE TABLE usuario(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	CONSTRAINT USUARIO_ID_PK PRIMARY KEY(id)
);

CREATE TABLE jogadores(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	chute INT NOT NULL,
	passe INT NOT NULL,
	marcacao INT NOT NULL,
	velocidade INT NOT NULL,
	CONSTRAINT JOGADORES_ID_PK PRIMARY KEY(id)
);